# Generated by Django 4.2.7 on 2024-09-13 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='borrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1500)),
                ('genre', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('num', models.IntegerField(null=True)),
                ('imprint', models.CharField(max_length=30)),
                ('due', models.DateField()),
                ('user', models.ForeignKey(db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=1500)),
                ('genre', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30, null=True)),
                ('num', models.IntegerField(null=True)),
                ('user', models.ForeignKey(db_column='users_id', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
