# Generated by Django 3.2.13 on 2026-09-15 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='cover_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
