# Generated by Django 3.2.25 on 2026-09-26 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_delete_emailverificationtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='copies',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='books',
            name='isbn',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='pages',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='books',
            name='publish_year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='genre',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='imprint',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
