# Generated by Django 4.1.7 on 2023-07-15 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_borrow_due'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='description',
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='description',
            field=models.TextField(max_length=1500),
        ),
    ]
