# Generated by Django 4.1.7 on 2023-07-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_books_description_alter_borrow_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
