# Generated by Django 4.1.7 on 2023-07-15 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_books_name_borrow_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrow',
            name='due',
            field=models.DateField(),
        ),
    ]
