# Generated by Django 4.1.7 on 2023-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_borrow_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='num',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='borrow',
            name='num',
            field=models.IntegerField(null=True),
        ),
    ]
